gg.toast("🤡 SCRİPT AKTİF EDİLDİ 🤡")

function Main()
menu = gg.multiChoice({
"🤡BYPASS ╚❑[Lᴏʙʙʏ]",
"🌹3RD FİX╚❑[𝙶𝚒𝚛𝚒𝚜]",
"🔙ÇIKIŞ",
}, nil, " 《 ᐯIᑭ ᗷYᑭᗩՏՏ ᑕOᗪᗴՏ ᑎOᗷᗩᑎՏᗴ᙭ 》")

if menu == nil then else 
if menu[1] == true then bypass1() end 
if menu[2] == true then fix2() end 
if menu[3] == true then
Exit() end end ZEUS = -1 end

function bypass1()
gg.setRanges(gg.REGION_C_ALLOC | gg.REGION_OTHER)
gg.searchNumber("67240961", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.refineNumber("67240961", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.getResults(69988)
gg.editAll("0", gg.TYPE_DWORD)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC | gg.REGION_OTHER)
gg.searchNumber("67240195", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.refineNumber("67240195", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.getResults(69988)
gg.editAll("0", gg.TYPE_DWORD)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC | gg.REGION_OTHER)
gg.searchNumber("67240706", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.refineNumber("67240706", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.getResults(69988)
gg.editAll("0", gg.TYPE_DWORD)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC | gg.REGION_OTHER)
gg.searchNumber("67240715", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.refineNumber("67240715", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.getResults(69988)
gg.editAll("0", gg.TYPE_DWORD)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC | gg.REGION_OTHER)
gg.searchNumber("67240450", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.refineNumber("67240450", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.getResults(69988)
gg.editAll("0", gg.TYPE_DWORD)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC | gg.REGION_OTHER)
gg.searchNumber("67240741", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.refineNumber("67240741", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.getResults(69988)
gg.editAll("0", gg.TYPE_DWORD)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC | gg.REGION_OTHER)
gg.searchNumber("67240449", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.refineNumber("67240449", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.getResults(69988)
gg.editAll("0", gg.TYPE_DWORD)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC | gg.REGION_OTHER)
gg.searchNumber("67241224", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.refineNumber("67241224", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.getResults(69988)
gg.editAll("0", gg.TYPE_DWORD)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC | gg.REGION_OTHER)
gg.searchNumber("67240993", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.refineNumber("67240993", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.getResults(69988)
gg.editAll("0", gg.TYPE_DWORD)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC | gg.REGION_OTHER)
gg.searchNumber("67240710", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.refineNumber("67240710", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.getResults(69988)
gg.editAll("0", gg.TYPE_DWORD)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC | gg.REGION_OTHER)
gg.searchNumber("67240270", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.refineNumber("67240270", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.getResults(69988)
gg.editAll("0", gg.TYPE_DWORD)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC | gg.REGION_OTHER)
gg.searchNumber("67240709", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.refineNumber("67240709", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.getResults(69988)
gg.editAll("0", gg.TYPE_DWORD)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC | gg.REGION_OTHER)
gg.searchNumber("67240270", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.refineNumber("67240270", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.getResults(69988)
gg.editAll("0", gg.TYPE_DWORD)
gg.clearResults()
gg.toast("LOBBY BYPASS AKTİF İYİ OYUNLAR ❤️ ")
end

function fix2()
gg.alert("🌹MERHABA ROOTSUZSUNUZ VE 3RD BAN YİYORSUNUZ BUNU HESABA GİRİŞ EKRANINDA ÇALIŞTIRDIKTAN SORNA HESABA GİRİN VİRTUAL FİXLİ İSE 10 SENE BAN YİYEBİLİRSİNİZ İYİ GÜNLER BİDAKİ GÜNCELLEMELERİN HABERİ İÇİN JOİN = https://t.me/bypasscodess 🌹")
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":/data/user/0/com.tencent", gg.TYPE_BYTE)
gg.getResults(99999)
gg.editAll("116", gg.TYPE_BYTE)
gg.clearResults()
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":/data/user/0/com.tencent", gg.TYPE_BYTE)
gg.getResults(99999)
gg.editAll("116", gg.TYPE_BYTE)
gg.clearResults()
gg.toast("🌹 3rd FİX AKTİF 🌹")
end

function Exit()
  gg.alert("✨𝐊𝐄𝐍𝐃İ𝐍𝐄 İ𝐘İ 𝐁𝐀𝐊✨\n", "𝐒𝐄𝐍𝐃𝐄 ❤️")
  print("❣️KENDİNE İYİ BAK❣️")
  print("☆   ┌─┐   .─┐☆ ★𝐇İ𝐋𝐄 𝐌𝐎𝐁İ𝐋𝐄★")
  print("    │▒│ /▒/ ")
  print("    │▒│/▒/    𝐒𝐂𝐑𝐈𝐏𝐓 :- 𝐛𝐲 𝚉𝙴𝚄𝚂🛡")
  print("    │▒/▒/─┬─┐")
  print("    │▒│▒|▒│▒│ 𝙾𝙽𝙻𝙸𝙽𝙴 ❤️")
  print("┌┴─┴─┐-┘─┘  ")
  print("│▒┌──┘▒▒▒│ 𝐒𝐂𝐑𝐈𝐏𝐓 :- 𝐛𝐲 𝚉𝙴𝚄𝚂 💙")
  print("└┐▒▒▒▒▒▒┌┘ ")
  print("    └┐▒▒▒▒┌┘  𝙾𝙽𝙻𝙸𝙽𝙴 ❤")
  print("▄︻̷̿┻̿═━一 𝚉𝙴𝚄𝚂")
  print("▄︻̷̿┻̿═━一 ")
  gg.skipRestoreState()
gg.setVisible(true)
os.exit()
 end

while true do
  if gg.isVisible(true) then
    ZEUS = 1
    gg.setVisible(false)
  end
  gg.clearResults()
  if ZEUS == 1 then
    Main()
  end
end

